### PR TITLE
Feature/loadImageFromPromise callbacks

### PR DESCRIPTION
**Pull request by adreyfus**
Makes possible to execute a callback on the newly created image, before to resolve it.

### CODE REVIEW

**Comment by dannyrb** [comment]
Out of curiosity, what use cases do you see this callback being used for? What prompted you to add it?

**Comment by adreyfus** [comment]
Hi, I use this callback to compute and add specific informations in all loaded images.

**Comment by dannyrb** [comment]
@swederik, this looks good to merge to me :+1:
It may be worth creating a companion issue to add documentation around callbacks

**Comment by swederik** [comment]
Thanks!

**Pull request merged**
