### PR TITLE
External modules2

### PR DESCRIPTION
**Pull request by kofifus**
This is one of a set of 3 PRs to cornerstone, cornerstoneTools and cornerstoneWADOImageLoader

- external is now a default export
- added $ and dicomParser to external for completion - they can now be injected as well
- removed externalModulesES6modules.js as it is no longer needed
- replaced the register.js mechanism with calls in externalModules.js - the register.js mechanism caused an import mutual dependency loop between register.js and externalModules.js

### CODE REVIEW

**Comment by swederik** [comment]
Hi there,

I can't merge this PR. I've tried to rebase it and even though the browser examples seem to work, the tests fail every time and I don't see why.

It looks like a dataSet is in the cache, but when it is retrieved it is not there. I think there are two instances of Cornerstone somehow. I guess it's related to the changes to the register mechanism.

I tried on this branch: https://github.com/chafey/cornerstoneWADOImageLoader/tree/kofifus-externalModules2

**Comment by kofifus** [comment]
Thx!

Looking at integration_test.js it has:
`import { external } from '../src/externalModules.js';`

This should be:
`import  external  from '../src/externalModules.js';`

As externalModules.js now has a default export. But I'm not sure if that is indeed the problem.

Can you please explain how do I run the tests ?

**Comment by kofifus** [comment]
fixed externals in tests

**Comment by swederik** [comment]
That's not the problem. I still don't know what it is, but I can't run the tests. You can try it yourself with:

````bash
npm test
````

**Pull request closed without merging**
