### PR TITLE
Feature/dataSetCache infos

### PR DESCRIPTION
**Pull request by adreyfus**
_`dataSetCacheManager.getInfo()`

_Trigger an event `'datasetscachechanged'` when the dataSets cache changes

### CODE REVIEW

**Comment by adreyfus** [comment]
I will adapt this PR to the new events system.

**Comment by dannyrb** [comment]
My only comments would be:

1. We use `.get` to retrieve the cache. Instead of `.getCacheInfo`, maybe `.getInfo` would be more in line with current convention?
2. It'd be easier for me to justify merging this without annoying @swederik if you sneaked in some unit tests for the new functionality (:

**Comment by adreyfus** [comment]
I don't know how to test the triggered event.

**Comment by adreyfus** [comment]
I chose `getCacheInfo()` to be consistent with `cornerstone.imageCache.getCacheInfo()`

**Comment by dannyrb** [comment]
Ah. Maybe @swederik would have a preference? But I feel like `datasetCacheManager.getInfo()` should be verbose enough

**Pull request merged**
