### PR TITLE
Add support for YBR_FULL_422 photometric interpretation

### PR DESCRIPTION
**Pull request by jmhmd**
This adds correct conversion of YBR_FULL_422 to rgba. Tested with a multiframe ultrasound that wasn't displaying correctly. Please test with other examples if you have them to confirm I've done this correctly.

### CODE REVIEW

**Comment by malaterre** [comment]
I am guessing this should fix #304

**Comment by dannyrb** [comment]
@jmhmd, is this a fix for #309? Are you able to add a `test image` and `test case` for this?

**Comment by jmhmd** [comment]
Not sure this will fix #309, the problem I was having was a garbled image displayed, but no errors thrown. The error message posted in that issue might be a different problem. I’ll try to add a test image soon.

**Comment by malaterre** [comment]
Just a quick FYI I did provide a link to a DataSet to reproduce the issue. Is it working now ? I'll try the live WADO example later today to check.

**Comment by jmhmd** [comment]
I added a test image - It's huge, the only YBR_FULL_422 images I have are big multiframe cine images.

I'm not sure how best to add a test for this- it wasn't producing an error before, just incorrectly interpreting it as RGB and displaying funny. Is there a good way to write a test for that?

@malaterre I am getting the same error as you with this branch and the test image you provided. It seems to be a different issue.

**Comment by jmhmd** [comment]
I have added a fix both to my own YBR conversion code and also to the getUncompressedImageFrame function that should fix #309. The image @malaterre provided in that issue now displays correctly.

**Comment by swederik** [comment]
Thanks everyone!

**Pull request merged**
