### PR TITLE
Feature/decache function in image load object

### PR DESCRIPTION
**Pull request by adreyfus**
_contains change of the PR #158 (bugfix/loadImageFromDataSet shall not decache)

_add the decache function to the imageLoadObject instead of the image, because we can need to decache the dataSet even if the image is not constructed. imageLoadObject.decache is checked by cornerstone because of the PR cornerstonejs/cornerstone#154.

### CODE REVIEW

**Comment by dannyrb** [comment]
If this contains PR #158, can we close  PR #158?

I like the changes. @swederik, can we merge this? Are there versioning concerns over changing the params the default `addDecache` callback takes? This feels like a cleaner/smarter approach to me.

**Comment by adreyfus** [comment]
If this PR is accepted, we can close PR #158. I try to cut as much as possible because you accept easier small PRs.

**Comment by dannyrb** [comment]
I'm comfortable merging most things in _cornerstoneTools_ and _cornerstoneWebImageLoader_, still working on my comfort level for this and core. I've requested a review from @swederik.

As far as I can tell, this is good to merge :+1:

The only thing that might be worth looking into, in my opinion, is using `async`/`await` to [avoid nesting promises](https://blog.patricktriest.com/what-is-async-await-why-should-you-care/)

**Comment by swederik** [comment]
Looks good! Thanks!

**Pull request merged**
