### PR TITLE
Remove explicit server-side transcoding (#357)

### LINKED ISSUE #357: WADO-RS: loadImage client always request server-side transcoding
If my understanding is correct, the WADO-RS loadImage() function is setup to always request server-side transcoding:

* https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/wadors/loadImage.js#L66

Would it be possible to read `mediaType` from `options` function parameter instead ?

### PR DESCRIPTION
**Pull request by malaterre**
Closes #357

### CODE REVIEW

**Comment by malaterre** [comment]
@sjodogne

**Comment by jodogne** [comment]
> @jodogne

If this can be useful, here is the reference in the DICOM standard: http://dicom.nema.org/medical/dicom/2020e/output/chtml/part18/sect_8.7.3.5.2.html

_"The wildcard value "*" indicates that the user agent will accept any Transfer Syntax. This allows, for example, the origin server to respond without needing to transcode an existing representation to a new Transfer Syntax, or to respond with the Explicit VR Little Endian Transfer Syntax regardless of the Transfer Syntax stored, unless the origin server has only access to the pixel data in lossy compressed form or the pixel data in a lossless compressed form that is of such length that it cannot be encoded in the Explicit VR Little Endian Transfer Syntax."_

**Comment by malaterre** [comment]
Technically the correct `Accept` header (thanks @gunterze) is: `-H 'accept: */*'`. Since this is incompatible with current orthanc implementation, I'll not submit as PR for now.

**Comment by swederik** [comment]
Thanks!

**Pull request merged**
