### PR TITLE
Fix issue cornerstoneTools#806

### PR DESCRIPTION
**Pull request by sisobus**
I implemented a feature that uses ImagePixelSpacing (x00181164) when PixelSpacing (x00280030) is missing. I did refer to comment below.

https://github.com/cornerstonejs/cornerstoneTools/issues/806#issuecomment-461716232

### CODE REVIEW

**Comment by dannyrb** [comment]
This looks okay to me. Preserves original functionality, but uses the new tag as a fallback. So this shouldn't be breaking. Thank you for this PR, and for taking the time to add unit tests.

**Comment by chafey** [comment]
This change can result in incorrect measurements leading to patient safety issues and should be rejected.  ImagerPixelSpacing is NOT the same thing as PixelSpacing and cannot be used as such (or at least not by default).  Using ImagerPixelSpacing in this manner should be opt-in (not on by default) and probably handled at the tool level (not the loader).  Proper 2d measurement on projection radiographs requires calibration - you can find more information on this in comp.protocols.dicom.

**Comment by dannyrb** [comment]
Thanks for raising a flag, @chafey! I'll revert the PR.

**Comment by dannyrb** [comment]
Revert applied here: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/262

**Comment by Zaid-Safadi** [comment]
Hi @chafey, can you please elaborate more on why using imagerPixelSpacing (0018,1164)is not recommended?

Currently there is a bug in OHIF as it is completely ignoring the imagerPixelSpacing and when there is no pixel spacing (0028,0030) it is displaying the pixel values (in mm unit which is double bug!) see https://github.com/OHIF/Viewers/issues/201

According to a very old post by David C. ImagerPixelSpacing takes priority over PixelSpacing: 
https://groups.google.com/forum/#!topic/comp.protocols.dicom/XkOfFrMzH1Y

The standard also is clear about this, pixel spacing is used for the calibrated value and it shouuld be the same as the ImagerPixelSpacing if there is no calibration:
http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_10.7.html#sect_10.7.1.1

**Comment by Zaid-Safadi** [comment]
One more thought, if my understanding is correct, the opt-in should be the other way around based on Clunie's answer. 
If we have both the ImagerPixelSpacing (0018,1164) and pixel spacing (0028,0030) with different values, then we should display the ImagerPixelSpacing (0018,1164) and let the user opt-in to use the "calibrated value/pixel spacing"

**Comment by chafey** [comment]
The problem with using ImagerPixelSpacing (and measuring on film) is that it is not an accurate measurement due to the divergence of the beam that occurs in projection radiographs.  If you measure this way, it is 100% guaranteed to be off by 5-10% depending on beam divergence.  To accurately measure anything in a projection radiograph, you must calibrate with an object of known length placed at the same distance from the detector as the object you want to measure.  Using imagePixelSpacing will match what is measured on Film, but this is not a safe thing to do in the first place!  If the application provides the suitable warnings to the user, it is as acceptable to use imagerPixelSpacing, but cornerstone is NOT an application so it doesn't have this luxury and this must therefore be "opt in" by the application with clear documentation explaining what the consequences are if they opt in

**Comment by Zaid-Safadi** [comment]
Thanks for the info @chafey. I am digging more into this and seems there has been a round of correction in the standard to clarify the usage of these attributes. For reference, here are the latest information I can find:
Display Cases and recommendations: https://groups.google.com/forum/#!topic/comp.protocols.dicom/jJ4k6umuNoM

DICOM correction (CP 586): ftp://medical.nema.org/medical/dicom/final/cp586_ft.pdf

My take on this since every application needs to make a decision on this -**including not supporting imagerPixelSpacing**- the cornerstone library (WADO loader) should abstract all these details from the user and provide a way to support all pixel spacing tags with an explanation of what is being used (e.g. **calibrated, detector plane, unknown**), even possibly with some configuration for defaults.

**Comment by raym27** [comment]
Hi,
We are trying to incorporate a DR long length imaging (DX images) of AP and Lateral whole lower limb to be reconstructed into a Zimmer 3D processor. This processor requires the DX image’s Imager Pixel Spacing value (0018,1164).
Question: Is it normal for the same patient DX images, the AP and Lateral to be having a different Imager Pixel Spacing value (0018,1164) ? And what would cause the values to be different between AP and Lateral images?

Thanks 😊

**Pull request merged**
