### PR TITLE
Feature/loadImage improvements

### PR DESCRIPTION
**Pull request by adreyfus**
_Add the decache function to the image promise instead of the image, because we can need to decache the dataSet even if the image is not constructed.

_`loadImageFromPromise()` rejects the error and the dataSet if the creation of the image failed, instead of doing nothing or throwing an error (like PR #107)

_parameter `createImageOptions` instead of `options` (much clearer name)

_imageDoneCallback in `loadImageFromPromise()`

### CODE REVIEW

**Comment by adreyfus** [comment]
There are still problems when the cache is full. I will open the Pull request once I have finished.

**Comment by adreyfus** [comment]
I will resolve conflicts when I have time ( again :-/ )

**Comment by dannyrb** [comment]
@adreyfus, if you're finding that a PR is ready for merge, and it feels like we're overlooking it, please feel free to `@mention` myself or @swederik so we can weigh in. I appreciate your contributions, and want to make sure we respond in a timely manner so we can make a decision on what needs to be done for your code to be merged :+1:

**Comment by adreyfus** [comment]
I close this PR because it's replaced by smaller PRs #159, #107, and #160.

**Pull request closed without merging**
