### PR TITLE
Bugfix/remove the promise regardless of success or failure

### PR DESCRIPTION
**Pull request by adreyfus**
Shall remove the promise regardless of success or failure, but removed only in case of success.

This bug was introduced in commit 4172f78bb703a3d33e0c42fb598089127910059c, when replacing Deferred by Promises.

### CODE REVIEW

**Comment by adreyfus** [comment]
PhantomJS tests fail even without my change.

**Comment by adreyfus** [comment]
Errors before the change:
```
decodeImageFrame should properly decode LittleEndianImplicitTransferSyntax FAILED
	TypeError: undefined is not a constructor (evaluating 'cornerstone.triggerEvent(cornerstone.events, 'cornerstoneimageloadstart', eventData)') (test/decoders_test.js:3459)
```
So I guess `cornerstone.triggerEvent` is `undefined` ?

This code line is in in `xhrRequest.js:39`

**Comment by swederik** [comment]
Thanks Aloïs!

**Comment by adreyfus** [comment]
`Promise.always(..)` works fine with chrome, but I don't see it in the standard. Shall I replace by 
```
// Remove the promise regardless of success or failure
then(() => {
        delete promises[uri];
      }, () => {
        delete promises[uri];
      });
```

?

**Pull request merged**
