### PR TITLE
Feature/use wadouri.loadimage with other loader

### PR DESCRIPTION
**Pull request by adreyfus**
Related to issue #165.

### CODE REVIEW

**Comment by dannyrb** [comment]
It looks like you're allow the user to override the default `loader` for `wadouri`.

Currently, the `loader` used is based on the `scheme` you registered the `loader` with. In what scenarios would you _want_ to override the loader associated with the scheme?

What functionality does this add that registering a new scheme + loader does not?

**Comment by adreyfus** [comment]
I propose to continue this conversation in the related issue (#165.).

**Comment by swederik** [comment]
I am as confused as @dannyrb. 

This is quite a weird approach, but if you are using it for some WADO-derived approaches, I guess it's fine with me since it's a very small amount of code.

**Comment by lyan2000** [comment]
This PR allows the override of loader, but it will not work if used within the context of image stack tool. The stack data only contains imageId's, not options.

**Comment by lyan2000** [comment]
> It looks like you're allow the user to override the default `loader` for `wadouri`.
> 
> Currently, the `loader` used is based on the `scheme` you registered the `loader` with. In what scenarios would you _want_ to override the loader associated with the scheme?
> 
> What functionality does this add that registering a new scheme + loader does not?

My understanding is that the wadouri loader does the following
1. retrieve the data into a buffer
2. use dicom parser to decode the buffer and create an image object
3. cache some meta data so that it can be used later

Step 1 is hard coded to either XHR or file. The code in step 2 is quite involved. So if the user wants to create image from DICOM stream other than XHR or file, the simplest way is to override the loader, which will avoid lots of copy/paste.

I am using this option right now, but stumbled on the stack tool in cornerstoneTools.

**Pull request merged**
